#!/usr/bin/env bash
# firtool.elf.strip --lowering-options=disallowLocalVariables,disallowPackedArrays,locationInfoStyle=wrapInAtSquareBracket $@
firtool.elf.strip --lowering-options=disallowLocalVariables,locationInfoStyle=wrapInAtSquareBracket $@
